### ISSUE TITLE
Peer Review for Derrik By Nate

### ISSUE THREAD

**Issue by ndeimler99** [2020-bgmp/demultiplexing-derrik-gratz#2]
Line 57 be careful overwriting the second index.  Maybe just check to see if index one is equal to the result of the rev complement function when index two is passed as a parameter.  Overwriting is losing real data.  Just a thought. 

So with your main workflow to demultiplex.  Maybe check for N first.  If the index sequence contains an N we do not care about the quality score of it.  Saves a little bit of time which would add up over a large file.  

Main Considerations:
	How are you opening the files? You do not want to open and close the file each time (more time consuming) 
How are you writing to the files? Maybe design a method that allows you to do this otherwise your code may be very repetitive for no reason.
	Overall good job with the right idea and the pseudocode was very easy to read.

Check points:
The algorithm does make sense and I can follow the logic
	The algorithm appears to do everything it is supposed to do
	The proposed functions are reasonable and act as standalone pieces of code.

**Comment by derrik-gratz** [comment]
- On line 57, it just overwrites a saved copy of the data (in my 2d list), not the actual file data. I could easily do it without overwritting that too, but it shouldn't be a problem unless I need to retain the original index sequence. I may avoid overwritting the local copy just in case I do need the actual sequence later. I'll just store the rev comp in a separate variable

- I think that would be better, my thought was 'if it's low quality, I don't care about the sequence' but quality calculations will be more intense than a simple character search, so that should be first. Thanks!

- File opening: good point, I neglected to mention my file opening technique. As per Pete's advice I will plan to keep them all open. And yes I plan to have a function for writting to a file based on the concatenated indices that I can just pass into a function. But I never specified that, so I will need to

Thanks for your feedback Nate! I missed a few things and I'm glad you caught them
